apiVersion: apps/v1
kind: Deployment
metadata:
  name: red-magic
  namespace: production
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: red-magic
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: red-magic
    spec:
      containers:
        - command:
            - bash
            - -c
            - yarn start
          envFrom:
            - configMapRef:
                name: red-panda-config
          image: registry.sendout.ai/red-magic:prod
          imagePullPolicy: Always
          name: red-magic
          ports:
            - containerPort: 3000
              name: red-magic
              protocol: TCP
            - containerPort: 3000
          resources: {}
      imagePullSecrets:
        - name: docker-credential
      nodeSelector:
        kubernetes.io/hostname: prospect-primary
---
apiVersion: v1
kind: Service
metadata:
  name: red-magic-svc
  namespace: production
spec:
  ports:
    - name: red-magic
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: red-magic
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-to-https@kubernetescrd
  labels:
    app: red-magic
  name: red-magic-ingress-sendout
  namespace: production
spec:
  rules:
    - host: app.sendout.ai
      http:
        paths:
          - backend:
              service:
                name: red-magic-svc
                port:
                  number: 3000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - app.sendout.ai
      secretName: sendout-red-magic-prod-tls-secret

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-to-https@kubernetescrd
  labels:
    app: red-magic
  name: red-magic-ingress-geniefy
  namespace: production
spec:
  rules:
    - host: app.geniefy.ai
      http:
        paths:
          - backend:
              service:
                name: red-magic-svc
                port:
                  number: 3000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - app.geniefy.ai
      secretName: geniefy-red-magic-prod-tls-secret
